name: centryl
author: Petar Sabev
description: Centryl Framework
version: 2.0.0

publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^2.1.0
  codemirror: ^0.6.1+5.61.0
  convert: ^3.0.0
  crypto: ^3.0.1
  csv: ^5.0.0
  excel: ^2.0.0-null-safety
  http: ^0.13.1
  http_server: ^1.0.0
  intl: ^0.17.0
  logging: ^1.0.1
  mailer: ^5.0.0
  path: ^1.8.0
  stack_trace: ^1.10.0
  cl_annotation:
    git: git@repo.centryl.org:centryl/cl_annotation.git
  pdf:
    git: git@repo.centryl.org:centryl/pdf.git
  cl_builder:
    git: git@repo.centryl.org:centryl/cl_builder.git
  template:
    git: git@repo.centryl.org:centryl/template.git
  task:
    git: git@repo.centryl.org:utils/task.git
  communicator:
    git: git@repo.centryl.org:centryl/communicator.git
  mapper:
    git: git@repo.centryl.org:centryl/mapper.git
  cl_gen:
    git: git@repo.centryl.org:centryl/cl_gen.git

dev_dependencies:
  build_runner: ^2.0.3
  build_web_compilers: ^3.0.0
  test: ^1.17.4