name: centryl
author: Petar Sabev
description: Centryl Framework
version: 2.0.0

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  args: ^1.6.0
  intl: ^0.16.1
  codemirror: ^0.5.20+5.57.0
  sass_builder: ^2.1.3
  http_server: ^0.9.8+3
  http: ^0.12.0+2
  path: ^1.6.4
  crypto: ^2.1.3
  convert: ^2.1.1
  mailer: 3.1.0
  csv: ^4.0.3
  resource: ^2.1.6
  stack_trace: ^1.9.3
  pdf:
    git: git@repo.centryl.org:centryl/pdf.git
  cl_builder:
    git: git@repo.centryl.org:centryl/cl_builder.git
  template:
    git: git@repo.centryl.org:centryl/template.git
  task:
    git: git@repo.centryl.org:utils/task.git
  communicator:
    git: git@repo.centryl.org:centryl/communicator.git
  mapper:
    git: git@repo.centryl.org:centryl/mapper.git
  cl_annotation:
    git: git@repo.centryl.org:centryl/cl_annotation.git
  cl_gen:
    git: git@repo.centryl.org:centryl/cl_gen.git

dependency_overrides:
  mapper:
    path: ../centryl_deps/mapper

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.3
  build_web_compilers: ^2.12.1