name: centryl
author: Petar Sabev
description: Centryl Framework
version: 2.0.0

publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  codemirror: ^0.5.21+5.58.0
  convert: ^2.1.1
  crypto: ^2.1.5
  csv: ^4.0.3
  #excel: ^1.1.5
  excel:
    git: git@repo.centryl.org:utils/excel.git
   # git: https://github.com/justkawal/excel.git
  #http: ^0.12.2
  http_server: ^0.9.8+3
  intl: ^0.17.0
  logging: ^0.11.4
  mailer: 3.2.1
  path: ^1.6.4
  resource: ^2.1.6
  sass_builder: ^2.1.3
  stack_trace: ^1.9.3
  pdf:
    git: git@repo.centryl.org:centryl/pdf.git
  cl_builder:
    git: git@repo.centryl.org:centryl/cl_builder.git
  template:
    git: git@repo.centryl.org:centryl/template.git
  task:
    git: git@repo.centryl.org:utils/task.git
  communicator:
    git: git@repo.centryl.org:centryl/communicator.git
  mapper:
    git: git@repo.centryl.org:centryl/mapper.git
  cl_annotation:
    git: git@repo.centryl.org:centryl/cl_annotation.git
  cl_gen:
    git: git@repo.centryl.org:centryl/cl_gen.git

dev_dependencies:
  build_runner: ^1.10.3
  build_web_compilers: ^2.12.1
  test: ^1.15.4