name: centryl
author: Petar Sabev
description: Centryl Framework
version: 2.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^1.6.0
  codemirror: any
  convert: ^2.1.1
  crypto: any
  csv: ^4.0.3
  excel: any
  http_server: any
  intl: ^0.17.0
  logging: any
  mailer: any
  path: ^1.6.4
  resource: ^2.1.6
  stack_trace: ^1.9.3
  cl_annotation:
    git: git@repo.centryl.org:centryl/cl_annotation.git
  pdf:
    git:
      url: git@repo.centryl.org:centryl/pdf.git
      ref: nullsafe
  cl_builder:
    git:
      url: git@repo.centryl.org:centryl/cl_builder.git
      ref: nullsafe
  template:
    git:
      url: git@repo.centryl.org:centryl/template.git
      ref: nullsafe
  task:
    git:
      url: git@repo.centryl.org:utils/task.git
      ref: nullsafe
  communicator:
    git:
      url: git@repo.centryl.org:centryl/communicator.git
      ref: nullsafe
  mapper:
    git:
      url: git@repo.centryl.org:centryl/mapper.git
      ref: nullsafe
  cl_gen:
    git:
      url: git@repo.centryl.org:centryl/cl_gen.git
      ref: nullsafe

dev_dependencies:
  build_runner: ^1.10.3
  build_web_compilers: ^2.12.1
  test: ^1.15.4