name: centryl
author: Petar Sabev
description: Centryl Framework
version: 2.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  codemirror: ^0.6.1+5.61.0
  convert: ^3.0.0
  crypto: ^3.0.1
  csv: ^5.0.0
  excel: ^2.0.0-null-safety
  http_server: any
  http: ^0.13.1
  intl: ^0.17.0
  logging: ^1.0.1
  mailer: ^5.0.0
  path: ^1.8.0
  resource: ^2.1.6
  stack_trace: ^1.10.0
  cl_annotation:
    git:
      url: git@repo.centryl.org:centryl/cl_annotation.git
      ref: nullsafe
  pdf:
    git:
      url: git@repo.centryl.org:centryl/pdf.git
      ref: nullsafe
  cl_builder:
    git:
      url: git@repo.centryl.org:centryl/cl_builder.git
      ref: nullsafe
  template:
    git:
      url: git@repo.centryl.org:centryl/template.git
      ref: nullsafe
  task:
    git:
      url: git@repo.centryl.org:utils/task.git
      ref: nullsafe
  communicator:
    git:
      url: git@repo.centryl.org:centryl/communicator.git
      ref: nullsafe
  mapper:
    git:
      url: git@repo.centryl.org:centryl/mapper.git
      ref: nullsafe
  cl_gen:
    git:
      url: git@repo.centryl.org:centryl/cl_gen.git
      ref: nullsafe

dev_dependencies:
  build_runner: ^2.0.1
  build_web_compilers: ^3.0.0
  test: ^1.17.2